# Generated by Django 5.1.4 on 2024-12-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
