# Generated by Django 5.1.4 on 2024-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0002_excelupload_newstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='uploadedfile',
            field=models.FileField(upload_to='imported_files'),
        ),
    ]
